#!/usr/bin/env python3
"""
Build a practical 3-tier review policy from weak-label risk scores.

Input:
- predictions CSV from train_weak_needs_review_model.py

Output:
- policy CSV with tier assignment per item
- summary JSON with thresholds, queue sizes, and weak-label diagnostics
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import List
EXCLUDED_VALIDATION_PREFIXES = ["main/Z_LEGACY_DO_NOT_TRANSLATE/"]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build review policy tiers from weak risk scores.")
    p.add_argument(
        "--predictions-csv",
        default="data/validation/weak-needs-review-es-AR-predictions.csv",
        help="Predictions CSV generated by train_weak_needs_review_model.py",
    )
    p.add_argument(
        "--target-auto-pct",
        type=float,
        default=0.02,
        help="Target fraction of all items for auto_review tier (0-1).",
    )
    p.add_argument(
        "--target-queue-pct",
        type=float,
        default=0.12,
        help="Target fraction of all items for auto_review+queue_review tiers combined (0-1).",
    )
    p.add_argument(
        "--output-prefix",
        default="data/validation/weak-needs-review-es-AR-policy",
        help="Output prefix (without suffix).",
    )
    return p.parse_args()


def parse_float(v, default=0.0):
    try:
        n = float(v)
        if n != n:
            return default
        return n
    except Exception:
        return default


def clamp01(v: float) -> float:
    return max(0.0, min(1.0, float(v)))


def is_excluded_item_id(item_id: str) -> bool:
    normalized = str(item_id or "").strip().lower()
    if not normalized:
        return False
    return any(normalized.startswith(p.lower()) for p in EXCLUDED_VALIDATION_PREFIXES)


def threshold_for_top_fraction(rows: List[dict], frac: float) -> float:
    if not rows:
        return 1.0
    frac = clamp01(frac)
    if frac <= 0:
        return 1.0
    if frac >= 1:
        return 0.0
    sorted_rows = sorted(rows, key=lambda r: r["p_review"], reverse=True)
    k = int(round(len(sorted_rows) * frac))
    k = max(1, min(k, len(sorted_rows)))
    return float(sorted_rows[k - 1]["p_review"])


def tier_for_score(p: float, t_auto: float, t_queue: float) -> str:
    if p >= t_auto:
        return "auto_review"
    if p >= t_queue:
        return "queue_review"
    return "pass"


def weak_metrics(rows: List[dict], review_tiers: set[str]) -> dict:
    # Weak-label diagnostics only; not true ground-truth metrics.
    tp = fp = tn = fn = 0.0
    for r in rows:
        y = int(r["y_weak_label"])
        wt = float(r["weight"])
        pred = 1 if r["policy_tier"] in review_tiers else 0
        if pred == 1 and y == 1:
            tp += wt
        elif pred == 1 and y == 0:
            fp += wt
        elif pred == 0 and y == 0:
            tn += wt
        else:
            fn += wt
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
    return {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "weighted_confusion": {"tp": tp, "fp": fp, "tn": tn, "fn": fn},
    }


def main() -> int:
    args = parse_args()
    pred_path = Path(args.predictions_csv)
    output_prefix = Path(args.output_prefix)
    output_prefix.parent.mkdir(parents=True, exist_ok=True)

    rows: List[dict] = []
    with pred_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if is_excluded_item_id(row.get("item_id", "")):
                continue
            rows.append(
                {
                    **row,
                    "p_review": parse_float(row.get("p_review"), 0.0),
                    "y_weak_label": int(parse_float(row.get("y_weak_label"), 0)),
                    "weight": parse_float(row.get("weight"), 1.0),
                }
            )
    if not rows:
        raise SystemExit(f"No rows in {pred_path}")

    target_auto = clamp01(args.target_auto_pct)
    target_queue = clamp01(args.target_queue_pct)
    if target_queue < target_auto:
        target_queue = target_auto

    t_auto = threshold_for_top_fraction(rows, target_auto)
    t_queue = threshold_for_top_fraction(rows, target_queue)
    # Ensure order: auto threshold should be >= queue threshold.
    if t_auto < t_queue:
        t_auto, t_queue = t_queue, t_auto

    for r in rows:
        r["policy_tier"] = tier_for_score(r["p_review"], t_auto, t_queue)

    n = len(rows)
    counts = {
        "auto_review": sum(1 for r in rows if r["policy_tier"] == "auto_review"),
        "queue_review": sum(1 for r in rows if r["policy_tier"] == "queue_review"),
        "pass": sum(1 for r in rows if r["policy_tier"] == "pass"),
    }
    shares = {k: (v / n if n else 0.0) for k, v in counts.items()}

    # Weak-label diagnostics:
    metrics_reviewed = weak_metrics(rows, {"auto_review", "queue_review"})
    metrics_auto_only = weak_metrics(rows, {"auto_review"})

    # Prioritized list for reviewer operations:
    ranked = sorted(rows, key=lambda r: r["p_review"], reverse=True)
    top_candidates = [
        {
            "item_id": r.get("item_id", ""),
            "p_review": r["p_review"],
            "policy_tier": r["policy_tier"],
            "y_weak_label": r["y_weak_label"],
            "final_score": r.get("final_score", ""),
            "composite_score": r.get("composite_score", ""),
            "ai_score": r.get("ai_score", ""),
            "score_source": r.get("score_source", ""),
            "split": r.get("split", ""),
        }
        for r in ranked[:150]
    ]

    out_csv = output_prefix.with_name(output_prefix.name + "-decisions.csv")
    out_json = output_prefix.with_name(output_prefix.name + "-summary.json")

    csv_headers = [
        "item_id",
        "lang_code",
        "p_review",
        "policy_tier",
        "y_weak_label",
        "weight",
        "score_band",
        "final_score",
        "composite_score",
        "ai_score",
        "semantic_score",
        "lexical_score",
        "score_source",
        "updated",
        "split",
    ]
    with out_csv.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=csv_headers)
        w.writeheader()
        for r in ranked:
            w.writerow({k: r.get(k, "") for k in csv_headers})

    summary = {
        "status": "ok",
        "inputs": {
            "predictions_csv": str(pred_path),
            "target_auto_pct": target_auto,
            "target_queue_pct": target_queue,
        },
        "thresholds": {
            "auto_review_min_p": t_auto,
            "queue_review_min_p": t_queue,
        },
        "counts": counts,
        "shares": shares,
        "weak_label_diagnostics": {
            "reviewed_tiers_combined": metrics_reviewed,
            "auto_review_only": metrics_auto_only,
        },
        "top_candidates": top_candidates,
        "outputs": {
            "decisions_csv": str(out_csv),
            "summary_json": str(out_json),
        },
        "notes": [
            "This policy is based on weak labels. Validate with periodic human audits.",
            "Tune target_auto_pct and target_queue_pct to match reviewer capacity.",
        ],
    }
    out_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(f"wrote {out_csv}")
    print(f"wrote {out_json}")
    print(
        "tiers: auto_review={auto} queue_review={queue} pass={pas}".format(
            auto=counts["auto_review"], queue=counts["queue_review"], pas=counts["pass"]
        )
    )
    print(f"thresholds: auto>={t_auto:.6f}, queue>={t_queue:.6f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

